global:
  country: DE
  org: My Org
  locality: Berlin
certs:
  - fileName: test
    CN: me.at.home
    CN_as_SAN: "false"
    CA: "false"
    SANs:
      - name: me
      - name: me.at
      - ip: 10.0.0.1
  - CN: me.at.home
    SANs:
      - name: me.at
